/**:
  ros__parameters:
    ekf_state_estimator:
      x0: [0.001, 0.001, 0.001, 0.001, 0.001, 0.1]
      p0: [
        1e3, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1e3, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 1e3, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1e3, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 1.0
      ]
      q: [
        0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.1
      ]

      x_max: [.inf, .inf, .inf, 2.0, 0.3, 20.0]
      x_min: [-.inf, -.inf, -.inf, -2.0, -0.3, -20.0]
      reset_on_timestamp_jump: true
